### ISSUE TITLE
Decide coding style

### ISSUE THREAD

**Issue by ghost** [diffr/diffr-c#4]
Reading C code with different coding styles is annoying. I am used to the BSD style documented here http://en.wikipedia.org/wiki/Indent_style#BSD_KNF_style

Toughts?

**Comment by w-martin** [comment]
Seems OK, but I'm wondering why 8 and 4 column indents and not 4 and 2:

``` c
// 8 and 4
if (data != NULL && res > 0) {
        if (JS_DefineProperty(cx, o, "data",
            STRING_TO_JSVAL(JS_NewStringCopyN(cx, data, res)),
            NULL, NULL, JSPROP_ENUMERATE) != 0) {
                QUEUE_EXCEPTION("Internal error!");
                goto err;
        }
        PQfreemem(data);
}

// 4 and 2
if (data != NULL && res > 0) {
    if (JS_DefineProperty(cx, o, "data",
      STRING_TO_JSVAL(JS_NewStringCopyN(cx, data, res)),
      NULL, NULL, JSPROP_ENUMERATE) != 0) {
        QUEUE_EXCEPTION("Internal error!");
        goto err;
    }
    PQfreemem(data);
}
```

Don't mind either way, though. :+1:

**Comment by jkozlowski** [comment]
Sure, fine by me as well, and I also prefer the 4/2 indents, no need to waste so much space :D So this is basically javaesque, apart from function braces on new lines and a new line after type information and before function name.

**Comment by ghost** [comment]
Yup. In fact I don't even follow the tabs convention and use two spaces for everything. Let's do 4 and 2, spaces not \t's.
